### ISSUE TITLE
Getting DB connection error as soon as I hit the app url locally

### ISSUE THREAD

**Issue by ishandutta2007** [GoogleCloudPlatform/nodejs-getting-started#2]
App listening at http://0.0.0.0:8080
Press Ctrl+C to quit.
/Users/dutishan/Documents/2-structured-data/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
TypeError: Cannot read property 'find' of undefined
    at /Users/dutishan/Documents/2-structured-data/books/model-mongodb.js:55:17
    at /Users/dutishan/Documents/2-structured-data/books/model-mongodb.js:45:23
    at /Users/dutishan/Documents/2-structured-data/node_modules/mongodb/lib/mongo_client.js:236:20
    at /Users/dutishan/Documents/2-structured-data/node_modules/mongodb/lib/db.js:203:14
    at null.<anonymous> (/Users/dutishan/Documents/2-structured-data/node_modules/mongodb/lib/server.js:226:9)

**Comment by jonparrott** [comment]
This is likely due to the app not being able to connect to your MongoDB instance.

A few questions:
1. Are you self-hosting on Compute Engine? If so:
  1. Is your mongo instance up? see http://console.developers.google.com/project/_/compute/instances
  2. Do you have a firewall rule setup to allow mongo? see http://console.developers.google.com/project/_/compute/networksDetail/global/networks/default
  3. Can you connect to your mongo instance locally using the mongo command line client?
2. If you're using mongolab, make sure your connection string is correct.

You also uncovered a bug where it doesn't return the error if the connection fails. I'll fix that and push shortly.

**Comment by jonparrott** [comment]
Commit 3962056d adds logging to the err message and fixes list from trying to use the collection if there's an error. If you checkout the latest 2-structured-data and try again, you should get a more helpful error message.

**Comment by jonparrott** [comment]
I'm going to close this issue as it's been inactive for a while. If you are still experiencing this issue, please feel free to comment on the issue.
