### ISSUE TITLE
PubSub worker: return 200 status code?

### ISSUE THREAD

**Issue by RicardoBelchior** [GoogleCloudPlatform/nodejs-getting-started#322]
Hi, 

(Sorry if this is a stupid question, this is my first PubSub experience)

In the PubSub worker, shouldn't we send a 200 status code when the book is successfully processed? When testing this in localhost the book is correctly processed but the request never ends.. 

I'm talking about this line:
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/1bbfd13a589adae6252dcbc86da5d682b9cdc8d3/6-pubsub/worker.js#L72

Does it have any implications on the way PubSub acknowledges the messages ? I was reading https://cloud.google.com/pubsub/docs/push and got a little confused.

**Comment by fhinkel** [comment]
@RicardoBelchior 👋 Thanks for raising the issue. cc @anguillanneuf could you chime in here? Thanks

**Comment by anguillanneuf** [comment]
@RicardoBelchior 👋  It does look like we're missing some code in this tutorial. 😞 When Pub/Sub tries to deliver a message to the pre-configured URL *`https://worker-dot-[YOUR-PROJECT-ID].appspot.com/endpoint`* as an HTTP POST request, it meets the `/endpoint` handler here: https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/1bbfd13a589adae6252dcbc86da5d682b9cdc8d3/6-pubsub/worker.js#L53

Since only these status codes 200, 201, 202, 204, or 102 are interpreted as message acknowledgements, yet we send none of them, Pub/Sub  would consider the delivery unsuccessful and keep attempting redelivery. 

@fhinkel I don't know Node.js that well. Do you think by adding `res.sendStatus(200)` at the end of the `/endpoint` handler code block does the job?

**Comment by RicardoBelchior** [comment]
hi , that's cool, at least i'm not crazy =)

i also noticed that if the book was not in the database the pub/sub message was being delivered for ever. that happened to me a few times during development..

i'm gonna post my final solution , if it helps.

The "if/else" condition at line 70
```javascript
  if (content.action && content.action === 'processBook' && content.bookId) {
    logging.info(`Received request to process book ${content.bookId}`);
    processBook(content.bookId, err => {
      if (err) {
        if (err.code) {

          if (err.code == 404) {
            return res.status(200).send("Could not find requested book, so we're skipping this message.");
          }

          return res.status(err.code).send(err.message);
        } else {
          return res.sendStatus(400);
        }
      }
      
      return res.sendStatus(200);
    });
  } else {
    logging.warn('Bad request', content);
    return res.sendStatus(400);
  }
```

And also returning a proper error code at findBooksInfo, line 129:

```javascript
function findBookInfo(book, cb) {
  queryBooksApi(book.title, (err, r) => {
    if (!err && !r.items) {
      err = {
        code: 404,
        message: 'BooksApi: Not found',
      };
    }
    if (err) {
      cb(err);
      return;
    }

.....
```

**Comment by fhinkel** [comment]
@RicardoBelchior Looks like you were able to resolve the issue. Please let us know if we should reopen this. Thanks.
