### ISSUE TITLE
Error: Cannot find module '/Users/chr/dev/nodejs-getting-started/3-binary-data/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'

### ISSUE THREAD

**Issue by shotlom** [GoogleCloudPlatform/nodejs-getting-started#54]
Hi, 

Due to security flaws, current best practise for an npm install appears to be:

```npm install --ignore-scripts```

For chapter 3-binary-data, I'm having trouble installing with the ignore-scripts flag. Under node v 6.0.0 & v 4.2.1

Error: Cannot find module '/Users/chr/dev/nodejs-getting-started/3-binary-data/node_modules/gcloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'

**Comment by ace-n** [comment]
([Blog post](http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability) for context on said security flaws.)

This may have been due to some package reorganization on Google's end.

I didn't see any errors when running `npm install --ignore-scripts` in the following Node versions - so I'm closing this for now. Feel free to re-open if this continues to be an issue.
`v6.7.0`
`v6.0.0`
`v4.7.0`
`v4.2.1`
