### ISSUE TITLE
catch Exceptions in pubsub

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/nodejs-getting-started#68]
_From @mytholog on August 3, 2016 8:37_
#### Environment details
- OS: Mac (Capitan)
- Node.js version: 4.4.7
- gcloud-node version: 0.37.0
#### Steps to reproduce
1. require `gcloud-node`
2. run code from https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/master/6-pubsub

``` js
"stack":[
  "Error: Deadline Exceeded",
  " at Function.GrpcService.decorateError_ (/node_modules/gcloud/lib/common/grpc-service.js:482:34)",
  " at Object.callback (/node_modules/gcloud/lib/common/grpc-service.js:247:35)",
  " at /node_modules/gcloud/node_modules/grpc/src/node/src/client.js:420:14"
],
"level":"error",
"message":"uncaughtException: Deadline Exceeded"
```

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1465_

**Comment by stephenplusplus** [comment]
Thanks for the report. We have a couple of blocking PRs to get to first, but I will look into this as soon as I can.

**Comment by ace-n** [comment]
To what degree should we be catching exceptions?

Personally, I'd err on the side of _not_ catching them unless they are not exceptional. If the sample halts and catches fire due to a truly exceptional (i.e. problematic) event, perhaps we could display a slightly better message to the user (along the lines of "Oh no, something went wrong!") - but we'd still have to give them the stack trace/exception type so they/we can debug it.

@jmdobry thoughts?

**Comment by jmdobry** [comment]
Is this reproducible with the latest `@google-cloud/pubsub`?

**Comment by ace-n** [comment]
@jmdobry Not from what I've seen on my machine (everything works fine) - that being said, this seems like a nondeterministic error.

@stephenplusplus @mytholog Can you clarify whether the intent of this issue was:
1) We should fix this particular error
2) We should catch errors within the getting started samples *(what I thought your point was initially)*
3) Something else entirely

**Comment by stephenplusplus** [comment]
Deferring to @mytholog.

**Comment by mytholog** [comment]
"@google-cloud/pubsub": "^0.3.0"

reproduced on the third or more run

```
{
    "message": "Deadline Exceeded",
    "stack": "Error: Deadline Exceeded\n    at /tmp/cl/node_modules/grpc/src/node/src/client.js:417:17",
    "code": 504,
    "metadata": {
      "_internal_repr": {}
    },
    "level": "error"
  }
  {
    "date": "Sat Oct 15 2016 10:19:56 GMT+0700 (+07)",
    "process": {
      "pid": 28741,
      "uid": 501,
      "gid": 20,
      "cwd": "/tmp/cl",
      "execPath": "/usr/local/Cellar/node/6.8.0/bin/node",
      "version": "v6.8.0",
      "argv": [
        "/usr/local/Cellar/node/6.8.0/bin/node",
        "/tmp/cl/worker.js"
      ],
      "memoryUsage": {
        "rss": 84951040,
        "heapTotal": 70103040,
        "heapUsed": 46127008
      }
    },
    "os": {
      "loadavg": [
        2.34619140625,
        1.7861328125,
        1.578125
      ],
      "uptime": 180497
    },
    "trace": [
      {
        "column": 17,
        "file": "/tmp/cl/node_modules/grpc/src/node/src/client.js",
        "function": null,
        "line": 417,
        "method": null,
        "native": false
      }
    ],
    "stack": [
      "Error: Deadline Exceeded",
      "    at /tmp/cl/node_modules/grpc/src/node/src/client.js:417:17"
    ],
    "level": "error",
    "message": "uncaughtException: Deadline Exceeded"
  }
  {
    "error": {
      "code": 504,
      "metadata": {
        "_internal_repr": {}
      }
    },
    "currentJobMessage": null,
    "level": "error",
    "message": "uncaughtException in worker"
  }
```

**Comment by ace-n** [comment]
@mytholog Which region does your project use? If you're using a region that is geographically far away from you (e.g. `europe-west1` may be better for someone in Russia than a `us`-based region), that may contribute to timeout issues.

Also, I'm assuming your issue revolves around this error specifically. If your argument is that exception handling needs to be improved, please let us know so we can steer things in that direction.
