### ISSUE TITLE
Using Cloud SQL with Node.js => "Error: connect ETIMEDOUT" on App Engine

### ISSUE THREAD

**Issue by fabLouis** [GoogleCloudPlatform/nodejs-getting-started#70]
Hi,

When I follows all the steps of the turorial [Using Cloud SQL with Node.js](https://cloud.google.com/nodejs/getting-started/using-cloud-sql), I have a error after the step "_Deploying the app to the App Engine flexible environment_". 

When the Node.js application runs on my local machine (step "_Running the app on your local machine_"), they are any problem to connect and use the MySQL (Seconde Generation) instance. 
But when the Node.js application is deployed on the App Engine, I immediately have this following error:
{ [Error: connect ETIMEDOUT]
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true,
    response: 'connect ETIMEDOUT' }

In fact, it's working when I add the 0.0.0.0/0 IP address to the Authorized Networks section but how to do in a production environment?

Thanks for you help!

**Comment by ace-n** [comment]
This is probably because of firewall settings. In a production environment, you have a few options:
1) Run everything on the same network (i.e. Google Cloud Platform VM instances)
2) Manually add the IP addresses of machines/networks that need access to Cloud SQL to the Authorized Networks section.

More information on Firewall settings can be found [here](https://cloud.google.com/compute/docs/networks-and-firewalls).

**Comment by jmdobry** [comment]
If you're using Second Generation Cloud SQL, then you should be using the Proxy, which does not require opening any firewall. https://cloud.google.com/sql/docs/sql-proxy

**Comment by tareqisleem94** [comment]
@jmdobry hi jmdobry, how do i use proxy to connect from nodejs to cloud sql

in my case i'm using sequelize library, and using the ipv4 of my instance to connect to it with user root and its password 

what will change after using proxy ?
